// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package com.google.pubsub.flic.common;

public final class Command {
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_pubsub_CommandRequest_descriptor;
  private static final
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pubsub_CommandRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
        "\n\rCommand.proto\022\006pubsub\032\033google/protobuf" +
            "/empty.proto\032\037google/protobuf/timestamp." +
            "proto\"\373\001\n\016CommandRequest\022.\n\nstart_time\030\001" +
            " \001(\0132\032.google.protobuf.Timestamp\022-\n\tstop" +
            "_time\030\002 \001(\0132\032.google.protobuf.Timestamp\022" +
            "\031\n\021number_of_workers\030\003 \001(\005\022\032\n\022restart_st" +
            "atistics\030\004 \001(\010\022\035\n\025max_messages_per_pull\030" +
            "\005 \001(\005\022\017\n\007project\030\006 \001(\t\022\r\n\005topic\030\007 \001(\t\022\024\n" +
            "\014subscription\030\010 \001(\t2T\n\021LoadtestFramework" +
            "\022?\n\013StartClient\022\026.pubsub.CommandRequest\032",
        "\026.google.protobuf.Empty\"\000B(\n\035com.google." +
            "pubsub.flic.commonB\007Commandb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[]{
                com.google.protobuf.EmptyProto.getDescriptor(),
                com.google.protobuf.TimestampProto.getDescriptor(),
            }, assigner);
    internal_static_pubsub_CommandRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_pubsub_CommandRequest_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pubsub_CommandRequest_descriptor,
        new java.lang.String[]{"StartTime", "StopTime", "NumberOfWorkers", "RestartStatistics", "MaxMessagesPerPull", "Project", "Topic", "Subscription",});
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }
  private Command() {}

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  public interface CommandRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pubsub.CommandRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
     */
    boolean hasStartTime();
    /**
     * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
     */
    com.google.protobuf.Timestamp getStartTime();
    /**
     * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();

    /**
     * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
     */
    boolean hasStopTime();
    /**
     * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
     */
    com.google.protobuf.Timestamp getStopTime();
    /**
     * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getStopTimeOrBuilder();

    /**
     * <code>optional int32 number_of_workers = 3;</code>
     */
    int getNumberOfWorkers();

    /**
     * <code>optional bool restart_statistics = 4;</code>
     */
    boolean getRestartStatistics();

    /**
     * <code>optional int32 max_messages_per_pull = 5;</code>
     */
    int getMaxMessagesPerPull();

    int getRequestRate();

    int getMessageSize();

    /**
     * <code>optional string project = 6;</code>
     */
    java.lang.String getProject();
    /**
     * <code>optional string project = 6;</code>
     */
    com.google.protobuf.ByteString
        getProjectBytes();

    /**
     * <code>optional string topic = 7;</code>
     */
    java.lang.String getTopic();
    /**
     * <code>optional string topic = 7;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <pre>
     * maybe a number of messages to expect rather than stop time?
     * </pre>
     *
     * <code>optional string subscription = 8;</code>
     */
    java.lang.String getSubscription();
    /**
     * <pre>
     * maybe a number of messages to expect rather than stop time?
     * </pre>
     *
     * <code>optional string subscription = 8;</code>
     */
    com.google.protobuf.ByteString
        getSubscriptionBytes();
  }

  /**
   * Protobuf type {@code pubsub.CommandRequest}
   */
  public  static final class CommandRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pubsub.CommandRequest)
      CommandRequestOrBuilder {
    public static final int START_TIME_FIELD_NUMBER = 1;
    public static final int STOP_TIME_FIELD_NUMBER = 2;
    public static final int NUMBER_OF_WORKERS_FIELD_NUMBER = 3;
    public static final int RESTART_STATISTICS_FIELD_NUMBER = 4;
    public static final int MESSAGE_SIZE_FIELD_NUMBER = 9;
    public static final int REQUEST_RATE_FIELD_NUMBER = 10;
    public static final int MAX_MESSAGES_PER_PULL_FIELD_NUMBER = 5;
    public static final int PROJECT_FIELD_NUMBER = 6;
    public static final int TOPIC_FIELD_NUMBER = 7;
    public static final int SUBSCRIPTION_FIELD_NUMBER = 8;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:pubsub.CommandRequest)
    private static final com.google.pubsub.flic.common.Command.CommandRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<CommandRequest>
        PARSER = new com.google.protobuf.AbstractParser<CommandRequest>() {
      public CommandRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommandRequest(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new com.google.pubsub.flic.common.Command.CommandRequest();
    }

    private com.google.protobuf.Timestamp startTime_;
    private com.google.protobuf.Timestamp stopTime_;
    private int numberOfWorkers_;
    private boolean restartStatistics_;
    private int messageSize_;
    private int requestRate_;
    private int maxMessagesPerPull_;
    private volatile java.lang.Object project_;
    private volatile java.lang.Object topic_;
    private volatile java.lang.Object subscription_;
    private byte memoizedIsInitialized = -1;
    // Use CommandRequest.newBuilder() to construct.
    private CommandRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CommandRequest() {
      numberOfWorkers_ = 0;
      restartStatistics_ = false;
      maxMessagesPerPull_ = 0;
      project_ = "";
      topic_ = "";
      subscription_ = "";
      requestRate_ = 0;
      messageSize_ = 0;
    }
    private CommandRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (startTime_ != null) {
                subBuilder = startTime_.toBuilder();
              }
              startTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(startTime_);
                startTime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (stopTime_ != null) {
                subBuilder = stopTime_.toBuilder();
              }
              stopTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stopTime_);
                stopTime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              numberOfWorkers_ = input.readInt32();
              break;
            }
            case 32: {

              restartStatistics_ = input.readBool();
              break;
            }
            case 40: {

              maxMessagesPerPull_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              project_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              topic_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              subscription_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.pubsub.flic.common.Command.internal_static_pubsub_CommandRequest_descriptor;
    }

    public static com.google.pubsub.flic.common.Command.CommandRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.pubsub.flic.common.Command.CommandRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.pubsub.flic.common.Command.CommandRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.pubsub.flic.common.Command.CommandRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.pubsub.flic.common.Command.CommandRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }

    public static com.google.pubsub.flic.common.Command.CommandRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.pubsub.flic.common.Command.CommandRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.pubsub.flic.common.Command.CommandRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.pubsub.flic.common.Command.CommandRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }

    public static com.google.pubsub.flic.common.Command.CommandRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.google.pubsub.flic.common.Command.CommandRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.google.pubsub.flic.common.Command.CommandRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<CommandRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.pubsub.flic.common.Command.internal_static_pubsub_CommandRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.pubsub.flic.common.Command.CommandRequest.class, com.google.pubsub.flic.common.Command.CommandRequest.Builder.class);
    }

    /**
     * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
     */
    public boolean hasStartTime() {
      return startTime_ != null;
    }

    /**
     * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
     */
    public com.google.protobuf.Timestamp getStartTime() {
      return startTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
    }

    /**
     * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder() {
      return getStartTime();
    }

    /**
     * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
     */
    public boolean hasStopTime() {
      return stopTime_ != null;
    }

    /**
     * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
     */
    public com.google.protobuf.Timestamp getStopTime() {
      return stopTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : stopTime_;
    }

    /**
     * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStopTimeOrBuilder() {
      return getStopTime();
    }

    /**
     * <code>optional int32 number_of_workers = 3;</code>
     */
    public int getNumberOfWorkers() {
      return numberOfWorkers_;
    }

    /**
     * <code>optional bool restart_statistics = 4;</code>
     */
    public boolean getRestartStatistics() {
      return restartStatistics_;
    }

    /**
     * <code>optional int32 max_messages_per_pull = 5;</code>
     */
    public int getMessageSize() {
      return messageSize_;
    }

    /**
     * <code>optional int32 max_messages_per_pull = 5;</code>
     */
    public int getRequestRate() {
      return requestRate_;
    }

    /**
     * <code>optional int32 max_messages_per_pull = 5;</code>
     */
    public int getMaxMessagesPerPull() {
      return maxMessagesPerPull_;
    }

    /**
     * <code>optional string project = 6;</code>
     */
    public java.lang.String getProject() {
      java.lang.Object ref = project_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        project_ = s;
        return s;
      }
    }

    /**
     * <code>optional string project = 6;</code>
     */
    public com.google.protobuf.ByteString
        getProjectBytes() {
      java.lang.Object ref = project_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        project_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>optional string topic = 7;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }

    /**
     * <code>optional string topic = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     * maybe a number of messages to expect rather than stop time?
     * </pre>
     *
     * <code>optional string subscription = 8;</code>
     */
    public java.lang.String getSubscription() {
      java.lang.Object ref = subscription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subscription_ = s;
        return s;
      }
    }

    /**
     * <pre>
     * maybe a number of messages to expect rather than stop time?
     * </pre>
     *
     * <code>optional string subscription = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSubscriptionBytes() {
      java.lang.Object ref = subscription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subscription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (startTime_ != null) {
        output.writeMessage(1, getStartTime());
      }
      if (stopTime_ != null) {
        output.writeMessage(2, getStopTime());
      }
      if (numberOfWorkers_ != 0) {
        output.writeInt32(3, numberOfWorkers_);
      }
      if (restartStatistics_ != false) {
        output.writeBool(4, restartStatistics_);
      }
      if (maxMessagesPerPull_ != 0) {
        output.writeInt32(5, maxMessagesPerPull_);
      }
      if (!getProjectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, project_);
      }
      if (!getTopicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, topic_);
      }
      if (!getSubscriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, subscription_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (startTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStartTime());
      }
      if (stopTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStopTime());
      }
      if (numberOfWorkers_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, numberOfWorkers_);
      }
      if (restartStatistics_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, restartStatistics_);
      }
      if (maxMessagesPerPull_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, maxMessagesPerPull_);
      }
      if (!getProjectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, project_);
      }
      if (!getTopicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, topic_);
      }
      if (!getSubscriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, subscription_);
      }
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.pubsub.flic.common.Command.CommandRequest)) {
        return super.equals(obj);
      }
      com.google.pubsub.flic.common.Command.CommandRequest other = (com.google.pubsub.flic.common.Command.CommandRequest) obj;

      boolean result = true;
      result = result && (hasStartTime() == other.hasStartTime());
      if (hasStartTime()) {
        result = result && getStartTime()
            .equals(other.getStartTime());
      }
      result = result && (hasStopTime() == other.hasStopTime());
      if (hasStopTime()) {
        result = result && getStopTime()
            .equals(other.getStopTime());
      }
      result = result && (getNumberOfWorkers()
          == other.getNumberOfWorkers());
      result = result && (getRestartStatistics()
          == other.getRestartStatistics());
      result = result && (getMaxMessagesPerPull()
          == other.getMaxMessagesPerPull());
      result = result && getProject()
          .equals(other.getProject());
      result = result && getTopic()
          .equals(other.getTopic());
      result = result && getSubscription()
          .equals(other.getSubscription());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasStartTime()) {
        hash = (37 * hash) + START_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getStartTime().hashCode();
      }
      if (hasStopTime()) {
        hash = (37 * hash) + STOP_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getStopTime().hashCode();
      }
      hash = (37 * hash) + NUMBER_OF_WORKERS_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfWorkers();
      hash = (37 * hash) + RESTART_STATISTICS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRestartStatistics());
      hash = (37 * hash) + MAX_MESSAGES_PER_PULL_FIELD_NUMBER;
      hash = (53 * hash) + getMaxMessagesPerPull();
      hash = (37 * hash) + PROJECT_FIELD_NUMBER;
      hash = (53 * hash) + getProject().hashCode();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (37 * hash) + SUBSCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getSubscription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public Builder newBuilderForType() { return newBuilder(); }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommandRequest> getParserForType() {
      return PARSER;
    }

    public com.google.pubsub.flic.common.Command.CommandRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code pubsub.CommandRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pubsub.CommandRequest)
        com.google.pubsub.flic.common.Command.CommandRequestOrBuilder {
      private com.google.protobuf.Timestamp startTime_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startTimeBuilder_;
      private com.google.protobuf.Timestamp stopTime_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> stopTimeBuilder_;
      private int numberOfWorkers_;
      private boolean restartStatistics_;
      private int maxMessagesPerPull_;
      private java.lang.Object project_ = "";
      private java.lang.Object topic_ = "";
      private java.lang.Object subscription_ = "";
      private int messageSize_;
      private int requestRate_;

      // Construct using com.google.pubsub.flic.common.Command.CommandRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.pubsub.flic.common.Command.internal_static_pubsub_CommandRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.pubsub.flic.common.Command.internal_static_pubsub_CommandRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.pubsub.flic.common.Command.CommandRequest.class, com.google.pubsub.flic.common.Command.CommandRequest.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
        }
      }

      public Builder clear() {
        super.clear();
        if (startTimeBuilder_ == null) {
          startTime_ = null;
        } else {
          startTime_ = null;
          startTimeBuilder_ = null;
        }
        if (stopTimeBuilder_ == null) {
          stopTime_ = null;
        } else {
          stopTime_ = null;
          stopTimeBuilder_ = null;
        }
        numberOfWorkers_ = 0;

        restartStatistics_ = false;

        maxMessagesPerPull_ = 0;

        project_ = "";

        topic_ = "";

        subscription_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.pubsub.flic.common.Command.internal_static_pubsub_CommandRequest_descriptor;
      }

      public com.google.pubsub.flic.common.Command.CommandRequest getDefaultInstanceForType() {
        return com.google.pubsub.flic.common.Command.CommandRequest.getDefaultInstance();
      }

      public com.google.pubsub.flic.common.Command.CommandRequest build() {
        com.google.pubsub.flic.common.Command.CommandRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.pubsub.flic.common.Command.CommandRequest buildPartial() {
        com.google.pubsub.flic.common.Command.CommandRequest result = new com.google.pubsub.flic.common.Command.CommandRequest(this);
        if (startTimeBuilder_ == null) {
          result.startTime_ = startTime_;
        } else {
          result.startTime_ = startTimeBuilder_.build();
        }
        if (stopTimeBuilder_ == null) {
          result.stopTime_ = stopTime_;
        } else {
          result.stopTime_ = stopTimeBuilder_.build();
        }
        result.numberOfWorkers_ = numberOfWorkers_;
        result.restartStatistics_ = restartStatistics_;
        result.maxMessagesPerPull_ = maxMessagesPerPull_;
        result.project_ = project_;
        result.topic_ = topic_;
        result.subscription_ = subscription_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.pubsub.flic.common.Command.CommandRequest) {
          return mergeFrom((com.google.pubsub.flic.common.Command.CommandRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.pubsub.flic.common.Command.CommandRequest other) {
        if (other == com.google.pubsub.flic.common.Command.CommandRequest.getDefaultInstance()) return this;
        if (other.hasStartTime()) {
          mergeStartTime(other.getStartTime());
        }
        if (other.hasStopTime()) {
          mergeStopTime(other.getStopTime());
        }
        if (other.getNumberOfWorkers() != 0) {
          setNumberOfWorkers(other.getNumberOfWorkers());
        }
        if (other.getRestartStatistics() != false) {
          setRestartStatistics(other.getRestartStatistics());
        }
        if (other.getMaxMessagesPerPull() != 0) {
          setMaxMessagesPerPull(other.getMaxMessagesPerPull());
        }
        if (!other.getProject().isEmpty()) {
          project_ = other.project_;
          onChanged();
        }
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          onChanged();
        }
        if (!other.getSubscription().isEmpty()) {
          subscription_ = other.subscription_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.pubsub.flic.common.Command.CommandRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.pubsub.flic.common.Command.CommandRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
       */
      public boolean hasStartTime() {
        return startTimeBuilder_ != null || startTime_ != null;
      }

      /**
       * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
       */
      public com.google.protobuf.Timestamp getStartTime() {
        if (startTimeBuilder_ == null) {
          return startTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
        } else {
          return startTimeBuilder_.getMessage();
        }
      }

      /**
       * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
       */
      public Builder setStartTime(com.google.protobuf.Timestamp value) {
        if (startTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          startTime_ = value;
          onChanged();
        } else {
          startTimeBuilder_.setMessage(value);
        }

        return this;
      }

      /**
       * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
       */
      public Builder setStartTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (startTimeBuilder_ == null) {
          startTime_ = builderForValue.build();
          onChanged();
        } else {
          startTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }

      /**
       * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
       */
      public Builder mergeStartTime(com.google.protobuf.Timestamp value) {
        if (startTimeBuilder_ == null) {
          if (startTime_ != null) {
            startTime_ =
              com.google.protobuf.Timestamp.newBuilder(startTime_).mergeFrom(value).buildPartial();
          } else {
            startTime_ = value;
          }
          onChanged();
        } else {
          startTimeBuilder_.mergeFrom(value);
        }

        return this;
      }

      /**
       * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
       */
      public Builder clearStartTime() {
        if (startTimeBuilder_ == null) {
          startTime_ = null;
          onChanged();
        } else {
          startTime_ = null;
          startTimeBuilder_ = null;
        }

        return this;
      }

      /**
       * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getStartTimeBuilder() {

        onChanged();
        return getStartTimeFieldBuilder().getBuilder();
      }

      /**
       * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder() {
        if (startTimeBuilder_ != null) {
          return startTimeBuilder_.getMessageOrBuilder();
        } else {
          return startTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
        }
      }

      /**
       * <code>optional .google.protobuf.Timestamp start_time = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
          getStartTimeFieldBuilder() {
        if (startTimeBuilder_ == null) {
          startTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getStartTime(),
                  getParentForChildren(),
                  isClean());
          startTime_ = null;
        }
        return startTimeBuilder_;
      }

      /**
       * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
       */
      public boolean hasStopTime() {
        return stopTimeBuilder_ != null || stopTime_ != null;
      }

      /**
       * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
       */
      public com.google.protobuf.Timestamp getStopTime() {
        if (stopTimeBuilder_ == null) {
          return stopTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : stopTime_;
        } else {
          return stopTimeBuilder_.getMessage();
        }
      }

      /**
       * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
       */
      public Builder setStopTime(com.google.protobuf.Timestamp value) {
        if (stopTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stopTime_ = value;
          onChanged();
        } else {
          stopTimeBuilder_.setMessage(value);
        }

        return this;
      }

      /**
       * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
       */
      public Builder setStopTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (stopTimeBuilder_ == null) {
          stopTime_ = builderForValue.build();
          onChanged();
        } else {
          stopTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }

      /**
       * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
       */
      public Builder mergeStopTime(com.google.protobuf.Timestamp value) {
        if (stopTimeBuilder_ == null) {
          if (stopTime_ != null) {
            stopTime_ =
              com.google.protobuf.Timestamp.newBuilder(stopTime_).mergeFrom(value).buildPartial();
          } else {
            stopTime_ = value;
          }
          onChanged();
        } else {
          stopTimeBuilder_.mergeFrom(value);
        }

        return this;
      }

      /**
       * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
       */
      public Builder clearStopTime() {
        if (stopTimeBuilder_ == null) {
          stopTime_ = null;
          onChanged();
        } else {
          stopTime_ = null;
          stopTimeBuilder_ = null;
        }

        return this;
      }

      /**
       * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getStopTimeBuilder() {

        onChanged();
        return getStopTimeFieldBuilder().getBuilder();
      }

      /**
       * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getStopTimeOrBuilder() {
        if (stopTimeBuilder_ != null) {
          return stopTimeBuilder_.getMessageOrBuilder();
        } else {
          return stopTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : stopTime_;
        }
      }

      /**
       * <code>optional .google.protobuf.Timestamp stop_time = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
          getStopTimeFieldBuilder() {
        if (stopTimeBuilder_ == null) {
          stopTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getStopTime(),
                  getParentForChildren(),
                  isClean());
          stopTime_ = null;
        }
        return stopTimeBuilder_;
      }

      /**
       * <code>optional int32 number_of_workers = 3;</code>
       */
      public int getNumberOfWorkers() {
        return numberOfWorkers_;
      }

      /**
       * <code>optional int32 number_of_workers = 3;</code>
       */
      public Builder setNumberOfWorkers(int value) {

        numberOfWorkers_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 number_of_workers = 3;</code>
       */
      public Builder clearNumberOfWorkers() {

        numberOfWorkers_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>optional bool restart_statistics = 4;</code>
       */
      public boolean getRestartStatistics() {
        return restartStatistics_;
      }

      /**
       * <code>optional bool restart_statistics = 4;</code>
       */
      public Builder setRestartStatistics(boolean value) {

        restartStatistics_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional bool restart_statistics = 4;</code>
       */
      public Builder clearRestartStatistics() {

        restartStatistics_ = false;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 max_messages_per_pull = 5;</code>
       */
      public int getMaxMessagesPerPull() {
        return maxMessagesPerPull_;
      }

      /**
       * <code>optional int32 max_messages_per_pull = 5;</code>
       */
      public Builder setMaxMessagesPerPull(int value) {

        maxMessagesPerPull_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 max_messages_per_pull = 5;</code>
       */
      public Builder clearMaxMessagesPerPull() {

        maxMessagesPerPull_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>optional string project = 6;</code>
       */
      public java.lang.String getProject() {
        java.lang.Object ref = project_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          project_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>optional string project = 6;</code>
       */
      public Builder setProject(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        project_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string project = 6;</code>
       */
      public com.google.protobuf.ByteString
          getProjectBytes() {
        java.lang.Object ref = project_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          project_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional string project = 6;</code>
       */
      public Builder setProjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
        checkByteStringIsUtf8(value);

        project_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string project = 6;</code>
       */
      public Builder clearProject() {

        project_ = getDefaultInstance().getProject();
        onChanged();
        return this;
      }

      /**
       * <code>optional string topic = 7;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>optional string topic = 7;</code>
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        topic_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string topic = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional string topic = 7;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
        checkByteStringIsUtf8(value);

        topic_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string topic = 7;</code>
       */
      public Builder clearTopic() {

        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }

      /**
       * <pre>
       * maybe a number of messages to expect rather than stop time?
       * </pre>
       *
       * <code>optional string subscription = 8;</code>
       */
      public java.lang.String getSubscription() {
        java.lang.Object ref = subscription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subscription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <pre>
       * maybe a number of messages to expect rather than stop time?
       * </pre>
       *
       * <code>optional string subscription = 8;</code>
       */
      public Builder setSubscription(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        subscription_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * maybe a number of messages to expect rather than stop time?
       * </pre>
       * <p>
       * <code>optional string subscription = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSubscriptionBytes() {
        java.lang.Object ref = subscription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subscription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <pre>
       * maybe a number of messages to expect rather than stop time?
       * </pre>
       *
       * <code>optional string subscription = 8;</code>
       */
      public Builder setSubscriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        subscription_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * maybe a number of messages to expect rather than stop time?
       * </pre>
       *
       * <code>optional string subscription = 8;</code>
       */
      public Builder clearSubscription() {

        subscription_ = getDefaultInstance().getSubscription();
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 number_of_workers = 3;</code>
       */
      public int getMessageSize() {
        return messageSize_;
      }

      /**
       * <code>optional int32 number_of_workers = 3;</code>
       */
      public Builder setMessageSize(int value) {

        messageSize_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 number_of_workers = 3;</code>
       */
      public Builder clearMessageSize() {

        messageSize_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 number_of_workers = 3;</code>
       */
      public int getRequestRate() {
        return requestRate_;
      }

      /**
       * <code>optional int32 number_of_workers = 3;</code>
       */
      public Builder setRequestRate(int value) {

        requestRate_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 number_of_workers = 3;</code>
       */
      public Builder clearRequestRate() {

        requestRate_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:pubsub.CommandRequest)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
