// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_packet.proto

package com.google.pubsub.flic.common;

public final class MessagePacketProto {
  private MessagePacketProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {}

  public interface MessagePacketOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:MessagePacket)
      com.google.protobuf.MessageOrBuilder {

    /** <code>optional string topic = 1;</code> */
    boolean hasTopic();
    /** <code>optional string topic = 1;</code> */
    String getTopic();
    /** <code>optional string topic = 1;</code> */
    com.google.protobuf.ByteString getTopicBytes();

    /** <code>optional string value = 2;</code> */
    boolean hasValue();
    /** <code>optional string value = 2;</code> */
    String getValue();
    /** <code>optional string value = 2;</code> */
    com.google.protobuf.ByteString getValueBytes();

    /** <code>optional string key = 3;</code> */
    boolean hasKey();
    /** <code>optional string key = 3;</code> */
    String getKey();
    /** <code>optional string key = 3;</code> */
    com.google.protobuf.ByteString getKeyBytes();
  }
  /** Protobuf type {@code MessagePacket} */
  public static final class MessagePacket extends com.google.protobuf.GeneratedMessage
      implements
      // @@protoc_insertion_point(message_implements:MessagePacket)
      MessagePacketOrBuilder {
    // Use MessagePacket.newBuilder() to construct.
    private MessagePacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }

    private MessagePacket() {
      topic_ = "";
      value_ = "";
      key_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private MessagePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default:
              {
                if (!parseUnknownField(
                    input, unknownFields,
                    extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            case 10:
              {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                topic_ = bs;
                break;
              }
            case 18:
              {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                value_ = bs;
                break;
              }
            case 26:
              {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                key_ = bs;
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
                .setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return MessagePacketProto.internal_static_MessagePacket_descriptor;
    }

    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return MessagePacketProto.internal_static_MessagePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessagePacketProto.MessagePacket.class,
              MessagePacketProto.MessagePacket.Builder.class);
    }

    private int bitField0_;
    public static final int TOPIC_FIELD_NUMBER = 1;
    private volatile Object topic_;
    /** <code>optional string topic = 1;</code> */
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /** <code>optional string topic = 1;</code> */
    public String getTopic() {
      Object ref = topic_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          topic_ = s;
        }
        return s;
      }
    }
    /** <code>optional string topic = 1;</code> */
    public com.google.protobuf.ByteString getTopicBytes() {
      Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile Object value_;
    /** <code>optional string value = 2;</code> */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /** <code>optional string value = 2;</code> */
    public String getValue() {
      Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /** <code>optional string value = 2;</code> */
    public com.google.protobuf.ByteString getValueBytes() {
      Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 3;
    private volatile Object key_;
    /** <code>optional string key = 3;</code> */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /** <code>optional string key = 3;</code> */
    public String getKey() {
      Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /** <code>optional string key = 3;</code> */
    public com.google.protobuf.ByteString getKeyBytes() {
      Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, topic_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, value_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, key_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, topic_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, value_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, key_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    public static MessagePacketProto.MessagePacket parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static MessagePacketProto.MessagePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static MessagePacketProto.MessagePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static MessagePacketProto.MessagePacket parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static MessagePacketProto.MessagePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static MessagePacketProto.MessagePacket parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static MessagePacketProto.MessagePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }

    public static MessagePacketProto.MessagePacket parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static MessagePacketProto.MessagePacket parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static MessagePacketProto.MessagePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(MessagePacketProto.MessagePacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code MessagePacket} */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:MessagePacket)
        MessagePacketProto.MessagePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return MessagePacketProto.internal_static_MessagePacket_descriptor;
      }

      protected FieldAccessorTable internalGetFieldAccessorTable() {
        return MessagePacketProto.internal_static_MessagePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessagePacketProto.MessagePacket.class,
                MessagePacketProto.MessagePacket.Builder.class);
      }

      // Construct using com.google.pubsub.flic.common.MessagePacketProto.MessagePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {}
      }

      public Builder clear() {
        super.clear();
        topic_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return MessagePacketProto.internal_static_MessagePacket_descriptor;
      }

      public MessagePacketProto.MessagePacket getDefaultInstanceForType() {
        return MessagePacketProto.MessagePacket.getDefaultInstance();
      }

      public MessagePacketProto.MessagePacket build() {
        MessagePacketProto.MessagePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MessagePacketProto.MessagePacket buildPartial() {
        MessagePacketProto.MessagePacket result = new MessagePacketProto.MessagePacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.topic_ = topic_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.key_ = key_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessagePacketProto.MessagePacket) {
          return mergeFrom((MessagePacketProto.MessagePacket) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessagePacketProto.MessagePacket other) {
        if (other == MessagePacketProto.MessagePacket.getDefaultInstance()) return this;
        if (other.hasTopic()) {
          bitField0_ |= 0x00000001;
          topic_ = other.topic_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000004;
          key_ = other.key_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessagePacketProto.MessagePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessagePacketProto.MessagePacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private Object topic_ = "";
      /** <code>optional string topic = 1;</code> */
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /** <code>optional string topic = 1;</code> */
      public String getTopic() {
        Object ref = topic_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            topic_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /** <code>optional string topic = 1;</code> */
      public com.google.protobuf.ByteString getTopicBytes() {
        Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>optional string topic = 1;</code> */
      public Builder setTopic(String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }
      /** <code>optional string topic = 1;</code> */
      public Builder clearTopic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /** <code>optional string topic = 1;</code> */
      public Builder setTopicBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }

      private Object value_ = "";
      /** <code>optional string value = 2;</code> */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /** <code>optional string value = 2;</code> */
      public String getValue() {
        Object ref = value_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /** <code>optional string value = 2;</code> */
      public com.google.protobuf.ByteString getValueBytes() {
        Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>optional string value = 2;</code> */
      public Builder setValue(String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /** <code>optional string value = 2;</code> */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /** <code>optional string value = 2;</code> */
      public Builder setValueBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      private Object key_ = "";
      /** <code>optional string key = 3;</code> */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /** <code>optional string key = 3;</code> */
      public String getKey() {
        Object ref = key_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /** <code>optional string key = 3;</code> */
      public com.google.protobuf.ByteString getKeyBytes() {
        Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>optional string key = 3;</code> */
      public Builder setKey(String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
        return this;
      }
      /** <code>optional string key = 3;</code> */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /** <code>optional string key = 3;</code> */
      public Builder setKeyBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MessagePacket)
    }

    // @@protoc_insertion_point(class_scope:MessagePacket)
    private static final MessagePacketProto.MessagePacket DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new MessagePacketProto.MessagePacket();
    }

    public static MessagePacketProto.MessagePacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated
    public static final com.google.protobuf.Parser<MessagePacket> PARSER =
        new com.google.protobuf.AbstractParser<MessagePacket>() {
          public MessagePacket parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            try {
              return new MessagePacket(input, extensionRegistry);
            } catch (RuntimeException e) {
              if (e.getCause() instanceof com.google.protobuf.InvalidProtocolBufferException) {
                throw (com.google.protobuf.InvalidProtocolBufferException) e.getCause();
              }
              throw e;
            }
          }
        };

    public static com.google.protobuf.Parser<MessagePacket> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessagePacket> getParserForType() {
      return PARSER;
    }

    public MessagePacketProto.MessagePacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  private static com.google.protobuf.Descriptors.Descriptor
      internal_static_MessagePacket_descriptor;
  private static com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessagePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    String[] descriptorData = {
      "\n\024message_packet.proto\":\n\rMessagePacket\022"
          + "\r\n\005topic\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022\013\n\003key\030\003 \001"
          + "(\tB3\n\035com.google.pubsub.flic.commonB\022Mes"
          + "sagePacketProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
    internal_static_MessagePacket_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_MessagePacket_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_MessagePacket_descriptor,
            new String[] {
              "Topic", "Value", "Key",
            });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
