# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/main/proto/loadtest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/main/proto/loadtest.proto',
  package='google.pubsub.loadtest',
  syntax='proto3',
  serialized_options=b'\n\035com.google.pubsub.flic.commonB\rLoadtestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dsrc/main/proto/loadtest.proto\x12\x16google.pubsub.loadtest\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x03\n\x0cStartRequest\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12.\n\nstart_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\rtest_duration\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x13\n\x0binclude_ids\x18\x05 \x01(\x08\x12?\n\x0epubsub_options\x18\x06 \x01(\x0b\x32%.google.pubsub.loadtest.PubsubOptionsH\x00\x12\x45\n\x11publisher_options\x18\x08 \x01(\x0b\x32(.google.pubsub.loadtest.PublisherOptionsH\x01\x12G\n\x12subscriber_options\x18\t \x01(\x0b\x32).google.pubsub.loadtest.SubscriberOptionsH\x01\x12\x13\n\x0b\x63pu_scaling\x18\n \x01(\x05\x42\t\n\x07optionsB\x10\n\x0e\x63lient_options\"\x0f\n\rStartResponse\"}\n\x10PublisherOptions\x12\x0c\n\x04rate\x18\x01 \x01(\x02\x12\x31\n\x0e\x62\x61tch_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x14\n\x0cmessage_size\x18\x04 \x01(\x05\"\x13\n\x11SubscriberOptions\"%\n\rPubsubOptions\x12\x14\n\x0csubscription\x18\x01 \x01(\t\"I\n\x11MessageIdentifier\x12\x1b\n\x13publisher_client_id\x18\x01 \x01(\x03\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x05\"\x0e\n\x0c\x43heckRequest\"\xc6\x01\n\rCheckResponse\x12\x15\n\rbucket_values\x18\x01 \x03(\x03\x12\x33\n\x10running_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x13\n\x0bis_finished\x18\x03 \x01(\x08\x12\x44\n\x11received_messages\x18\x04 \x03(\x0b\x32).google.pubsub.loadtest.MessageIdentifier\x12\x0e\n\x06\x66\x61iled\x18\x05 \x01(\x03\x32\xbc\x01\n\x0eLoadtestWorker\x12T\n\x05Start\x12$.google.pubsub.loadtest.StartRequest\x1a%.google.pubsub.loadtest.StartResponse\x12T\n\x05\x43heck\x12$.google.pubsub.loadtest.CheckRequest\x1a%.google.pubsub.loadtest.CheckResponseB.\n\x1d\x63om.google.pubsub.flic.commonB\rLoadtestProtob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_STARTREQUEST = _descriptor.Descriptor(
  name='StartRequest',
  full_name='google.pubsub.loadtest.StartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='google.pubsub.loadtest.StartRequest.project', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topic', full_name='google.pubsub.loadtest.StartRequest.topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='google.pubsub.loadtest.StartRequest.start_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_duration', full_name='google.pubsub.loadtest.StartRequest.test_duration', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='include_ids', full_name='google.pubsub.loadtest.StartRequest.include_ids', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pubsub_options', full_name='google.pubsub.loadtest.StartRequest.pubsub_options', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='publisher_options', full_name='google.pubsub.loadtest.StartRequest.publisher_options', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subscriber_options', full_name='google.pubsub.loadtest.StartRequest.subscriber_options', index=7,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpu_scaling', full_name='google.pubsub.loadtest.StartRequest.cpu_scaling', index=8,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='options', full_name='google.pubsub.loadtest.StartRequest.options',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='client_options', full_name='google.pubsub.loadtest.StartRequest.client_options',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=123,
  serialized_end=547,
)


_STARTRESPONSE = _descriptor.Descriptor(
  name='StartResponse',
  full_name='google.pubsub.loadtest.StartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=564,
)


_PUBLISHEROPTIONS = _descriptor.Descriptor(
  name='PublisherOptions',
  full_name='google.pubsub.loadtest.PublisherOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rate', full_name='google.pubsub.loadtest.PublisherOptions.rate', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_duration', full_name='google.pubsub.loadtest.PublisherOptions.batch_duration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='google.pubsub.loadtest.PublisherOptions.batch_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_size', full_name='google.pubsub.loadtest.PublisherOptions.message_size', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=691,
)


_SUBSCRIBEROPTIONS = _descriptor.Descriptor(
  name='SubscriberOptions',
  full_name='google.pubsub.loadtest.SubscriberOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=693,
  serialized_end=712,
)


_PUBSUBOPTIONS = _descriptor.Descriptor(
  name='PubsubOptions',
  full_name='google.pubsub.loadtest.PubsubOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscription', full_name='google.pubsub.loadtest.PubsubOptions.subscription', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=714,
  serialized_end=751,
)


_MESSAGEIDENTIFIER = _descriptor.Descriptor(
  name='MessageIdentifier',
  full_name='google.pubsub.loadtest.MessageIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='publisher_client_id', full_name='google.pubsub.loadtest.MessageIdentifier.publisher_client_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='google.pubsub.loadtest.MessageIdentifier.sequence_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=753,
  serialized_end=826,
)


_CHECKREQUEST = _descriptor.Descriptor(
  name='CheckRequest',
  full_name='google.pubsub.loadtest.CheckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=828,
  serialized_end=842,
)


_CHECKRESPONSE = _descriptor.Descriptor(
  name='CheckResponse',
  full_name='google.pubsub.loadtest.CheckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucket_values', full_name='google.pubsub.loadtest.CheckResponse.bucket_values', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='running_duration', full_name='google.pubsub.loadtest.CheckResponse.running_duration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_finished', full_name='google.pubsub.loadtest.CheckResponse.is_finished', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='received_messages', full_name='google.pubsub.loadtest.CheckResponse.received_messages', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='failed', full_name='google.pubsub.loadtest.CheckResponse.failed', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=845,
  serialized_end=1043,
)

_STARTREQUEST.fields_by_name['start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STARTREQUEST.fields_by_name['test_duration'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_STARTREQUEST.fields_by_name['pubsub_options'].message_type = _PUBSUBOPTIONS
_STARTREQUEST.fields_by_name['publisher_options'].message_type = _PUBLISHEROPTIONS
_STARTREQUEST.fields_by_name['subscriber_options'].message_type = _SUBSCRIBEROPTIONS
_STARTREQUEST.oneofs_by_name['options'].fields.append(
  _STARTREQUEST.fields_by_name['pubsub_options'])
_STARTREQUEST.fields_by_name['pubsub_options'].containing_oneof = _STARTREQUEST.oneofs_by_name['options']
_STARTREQUEST.oneofs_by_name['client_options'].fields.append(
  _STARTREQUEST.fields_by_name['publisher_options'])
_STARTREQUEST.fields_by_name['publisher_options'].containing_oneof = _STARTREQUEST.oneofs_by_name['client_options']
_STARTREQUEST.oneofs_by_name['client_options'].fields.append(
  _STARTREQUEST.fields_by_name['subscriber_options'])
_STARTREQUEST.fields_by_name['subscriber_options'].containing_oneof = _STARTREQUEST.oneofs_by_name['client_options']
_PUBLISHEROPTIONS.fields_by_name['batch_duration'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_CHECKRESPONSE.fields_by_name['running_duration'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_CHECKRESPONSE.fields_by_name['received_messages'].message_type = _MESSAGEIDENTIFIER
DESCRIPTOR.message_types_by_name['StartRequest'] = _STARTREQUEST
DESCRIPTOR.message_types_by_name['StartResponse'] = _STARTRESPONSE
DESCRIPTOR.message_types_by_name['PublisherOptions'] = _PUBLISHEROPTIONS
DESCRIPTOR.message_types_by_name['SubscriberOptions'] = _SUBSCRIBEROPTIONS
DESCRIPTOR.message_types_by_name['PubsubOptions'] = _PUBSUBOPTIONS
DESCRIPTOR.message_types_by_name['MessageIdentifier'] = _MESSAGEIDENTIFIER
DESCRIPTOR.message_types_by_name['CheckRequest'] = _CHECKREQUEST
DESCRIPTOR.message_types_by_name['CheckResponse'] = _CHECKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartRequest = _reflection.GeneratedProtocolMessageType('StartRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTREQUEST,
  '__module__' : 'src.main.proto.loadtest_pb2'
  # @@protoc_insertion_point(class_scope:google.pubsub.loadtest.StartRequest)
  })
_sym_db.RegisterMessage(StartRequest)

StartResponse = _reflection.GeneratedProtocolMessageType('StartResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTRESPONSE,
  '__module__' : 'src.main.proto.loadtest_pb2'
  # @@protoc_insertion_point(class_scope:google.pubsub.loadtest.StartResponse)
  })
_sym_db.RegisterMessage(StartResponse)

PublisherOptions = _reflection.GeneratedProtocolMessageType('PublisherOptions', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHEROPTIONS,
  '__module__' : 'src.main.proto.loadtest_pb2'
  # @@protoc_insertion_point(class_scope:google.pubsub.loadtest.PublisherOptions)
  })
_sym_db.RegisterMessage(PublisherOptions)

SubscriberOptions = _reflection.GeneratedProtocolMessageType('SubscriberOptions', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEROPTIONS,
  '__module__' : 'src.main.proto.loadtest_pb2'
  # @@protoc_insertion_point(class_scope:google.pubsub.loadtest.SubscriberOptions)
  })
_sym_db.RegisterMessage(SubscriberOptions)

PubsubOptions = _reflection.GeneratedProtocolMessageType('PubsubOptions', (_message.Message,), {
  'DESCRIPTOR' : _PUBSUBOPTIONS,
  '__module__' : 'src.main.proto.loadtest_pb2'
  # @@protoc_insertion_point(class_scope:google.pubsub.loadtest.PubsubOptions)
  })
_sym_db.RegisterMessage(PubsubOptions)

MessageIdentifier = _reflection.GeneratedProtocolMessageType('MessageIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEIDENTIFIER,
  '__module__' : 'src.main.proto.loadtest_pb2'
  # @@protoc_insertion_point(class_scope:google.pubsub.loadtest.MessageIdentifier)
  })
_sym_db.RegisterMessage(MessageIdentifier)

CheckRequest = _reflection.GeneratedProtocolMessageType('CheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKREQUEST,
  '__module__' : 'src.main.proto.loadtest_pb2'
  # @@protoc_insertion_point(class_scope:google.pubsub.loadtest.CheckRequest)
  })
_sym_db.RegisterMessage(CheckRequest)

CheckResponse = _reflection.GeneratedProtocolMessageType('CheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKRESPONSE,
  '__module__' : 'src.main.proto.loadtest_pb2'
  # @@protoc_insertion_point(class_scope:google.pubsub.loadtest.CheckResponse)
  })
_sym_db.RegisterMessage(CheckResponse)


DESCRIPTOR._options = None

_LOADTESTWORKER = _descriptor.ServiceDescriptor(
  name='LoadtestWorker',
  full_name='google.pubsub.loadtest.LoadtestWorker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=1046,
  serialized_end=1234,
  methods=[
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='google.pubsub.loadtest.LoadtestWorker.Start',
    index=0,
    containing_service=None,
    input_type=_STARTREQUEST,
    output_type=_STARTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Check',
    full_name='google.pubsub.loadtest.LoadtestWorker.Check',
    index=1,
    containing_service=None,
    input_type=_CHECKREQUEST,
    output_type=_CHECKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOADTESTWORKER)

DESCRIPTOR.services_by_name['LoadtestWorker'] = _LOADTESTWORKER

# @@protoc_insertion_point(module_scope)
